#ifndef APP_WEB_ASSETS_H_
#define APP_WEB_ASSETS_H_

static const char app_web_index_html[] =
"<!doctype html>"
"<html lang=\"fr\">"
"<head>"
"<meta charset=\"utf-8\">"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
"<title>Industrial Ethernet</title>"
"<link rel=\"stylesheet\" href=\"/app.css\">"
"</head>"
"<body>"
"<aside class=\"rail\">"
"<div class=\"brand\"><span class=\"mark\"><img src=\"/logo.jpg\" alt=\"\"></span><div><strong>Industrial Ethernet</strong><small>STM32H747 / Zephyr</small></div></div>"
"<nav>"
"<button class=\"nav active\" data-view=\"overview\">Dashboard</button>"
"<button class=\"nav\" data-view=\"registers\">Registres</button>"
"<button class=\"nav\" data-view=\"scanner\">Scanner</button>"
"<button class=\"nav\" data-view=\"network\">Reseau</button>"
"<button class=\"nav\" data-view=\"security\">Securite</button>"
"<button class=\"nav\" data-view=\"firmware\">Firmware</button>"
"</nav>"
"<div class=\"login-slot\"><span></span><div><b>Session locale</b><small>Login prevu phase 8</small></div></div>"
"</aside>"
"<main>"
"<header class=\"topbar\">"
"<div><h1 id=\"view-title\">Dashboard</h1><p id=\"view-subtitle\">Supervision temps reel de la carte industrielle</p></div>"
"<div class=\"topbar-actions\"><div class=\"status-line\"><span id=\"config-dot\" class=\"dot\"></span><span id=\"config-state\">-</span></div><button id=\"reboot-button\" class=\"reboot-button\" type=\"button\" title=\"Redemarrer la carte\" aria-label=\"Redemarrer la carte\">&#x21bb;</button></div>"
"</header>"
"<section id=\"overview\" class=\"view active\">"
"<div class=\"kpis\">"
"<article><span>Mode IP</span><strong id=\"kpi-mode\">-</strong></article>"
"<article><span>Adresse IP</span><strong id=\"kpi-ip\">-</strong></article>"
"<article><span>Connexions Modbus</span><strong id=\"kpi-connections\">-</strong></article>"
"<article><span>Heartbeat</span><strong id=\"kpi-heartbeat\">-</strong></article>"
"</div>"
"<div class=\"chart-grid\">"
"<section class=\"panel chart-panel\"><div class=\"panel-head\"><h2>Dashboard 1</h2><small>Preview</small></div><svg id=\"dashboard-chart-a\" viewBox=\"0 0 420 180\" role=\"img\"></svg></section>"
"<section class=\"panel chart-panel\"><div class=\"panel-head\"><h2>Dashboard 2</h2><small>Preview</small></div><svg id=\"dashboard-chart-b\" viewBox=\"0 0 420 180\" role=\"img\"></svg></section>"
"</div>"
"</section>"
"<section id=\"registers\" class=\"view\">"
"<section class=\"panel\"><div class=\"panel-head\"><h2>Holding registers</h2><small>Lecture/ecriture directe</small></div><div id=\"register-table\" class=\"reg-table\"></div></section>"
"</section>"
"<section id=\"scanner\" class=\"view\">"
"<section class=\"panel\"><div class=\"panel-head\"><h2>Fenetre scanner</h2><small>Mapping dynamique registers[40..49]</small></div><div id=\"scanner-table\" class=\"reg-table\"></div></section>"
"</section>"
"<section id=\"network\" class=\"view\"><section class=\"panel placeholder\"><h2>Configuration reseau</h2><p>Cette page accueillera le formulaire DHCP/statique, masque, gateway et sauvegarde persistante.</p><button disabled>Appliquer</button></section></section>"
"<section id=\"security\" class=\"view\"><section class=\"panel placeholder\"><h2>Securite et login</h2><p>Emplacement reserve pour la phase 8 : login, token, changement de mot de passe et HTTPS.</p><button disabled>Connexion</button></section></section>"
"<section id=\"firmware\" class=\"view\"><section class=\"panel placeholder\"><h2>Firmware update</h2><p>Emplacement reserve pour la phase 9 : upload binaire signe, progression et reboot controle.</p><button disabled>Selectionner un firmware</button></section></section>"
"</main>"
"<script src=\"/app.js\"></script>"
"</body>"
"</html>";

static const char app_web_css[] =
":root{--bg:#0f1318;--rail:#151b22;--panel:#f7f8fa;--ink:#17202a;--muted:#667085;--line:#d7dde5;--green:#12a66a;--red:#c84343;--amber:#c48628;--blue:#2f6fed;--steel:#263442}"
"*{box-sizing:border-box}body{margin:0;min-height:100vh;font-family:Inter,Segoe UI,Arial,sans-serif;background:#e9edf2;color:var(--ink);display:flex;letter-spacing:0}"
".rail{width:280px;background:var(--rail);color:#e9eef5;padding:22px 18px;display:flex;flex-direction:column;gap:24px;position:fixed;inset:0 auto 0 0}"
".brand{display:flex;gap:12px;align-items:center}.brand strong{display:block;font-size:17px}.brand small,.login-slot small{display:block;color:#9aa8b8;margin-top:3px}.mark{width:34px;height:34px;border-radius:7px;background:#fff;box-shadow:0 0 0 1px #ffffff20 inset;overflow:hidden;display:grid;place-items:center}.mark img{width:100%;height:100%;object-fit:cover;display:block}"
"nav{display:grid;gap:7px}.nav{height:40px;border:0;border-radius:6px;background:transparent;color:#c7d0dc;text-align:left;padding:0 12px;font-weight:650;cursor:pointer}.nav:hover{background:#202a34}.nav.active{background:#e9eef5;color:#17202a}"
".login-slot{margin-top:auto;border-top:1px solid #2d3744;padding-top:16px;display:flex;gap:10px;align-items:center}.login-slot span{width:10px;height:10px;border-radius:50%;background:var(--amber)}"
"main{margin-left:280px;width:calc(100% - 280px);padding:24px;min-height:100vh}.topbar{display:flex;justify-content:space-between;align-items:center;margin-bottom:20px;gap:16px}.topbar-actions{display:flex;align-items:center;gap:8px}h1{font-size:30px;margin:0 0 5px}p{margin:0;color:var(--muted);line-height:1.45}.status-line{display:flex;align-items:center;gap:10px;background:white;border:1px solid var(--line);border-radius:7px;padding:9px 10px}.dot{width:10px;height:10px;border-radius:50%;background:var(--red)}.dot.ok{background:var(--green)}button{border:1px solid #b9c2ce;background:#fff;border-radius:6px;height:34px;padding:0 12px;font-weight:700;color:#263442}button:not(:disabled){cursor:pointer}button:not(:disabled):hover{border-color:#6f7f91}button:disabled{opacity:.55}"
".reboot-button{width:36px;height:36px;padding:0;color:var(--steel);font-size:22px;line-height:1}.reboot-button:not(:disabled):hover{border-color:var(--blue);color:var(--blue)}.reboot-button:disabled{cursor:wait}"
".view{display:none}.view.active{display:block}.kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-bottom:16px}.kpis article,.panel{background:var(--panel);border:1px solid var(--line);border-radius:8px}.kpis article{padding:15px}.kpis span{display:block;color:var(--muted);font-size:13px}.kpis strong{display:block;margin-top:6px;font-size:23px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}"
".grid.two,.chart-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.panel{padding:16px}.panel-head{display:flex;justify-content:space-between;align-items:baseline;border-bottom:1px solid var(--line);padding-bottom:10px;margin-bottom:12px}.panel h2{font-size:18px;margin:0}.panel small{color:var(--muted)}.chart-panel{min-height:260px}.chart-panel svg{width:100%;height:210px;display:block}"
".compact-table,.reg-table{display:grid;gap:6px}.row{display:grid;grid-template-columns:185px 1fr 110px;gap:8px;align-items:center;min-height:34px;padding:6px 8px;background:white;border:1px solid #e1e6ed;border-radius:6px}.row label{font-weight:700;color:#334155}.reg-name{display:grid;gap:2px}.reg-name span{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.reg-name small{color:#7a8797;font-weight:600}.row code{color:#59677a;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.row input,.row select{width:100%;height:30px;border:1px solid #cbd3df;border-radius:5px;padding:0 8px;background:#fbfcfe}.row button{height:30px}.row.four{grid-template-columns:185px 1fr 110px}.row.readonly{grid-template-columns:185px 1fr}.reg-section{margin:10px 0 2px;color:#59677a;font-size:12px;font-weight:800;text-transform:uppercase;letter-spacing:.04em}.placeholder{min-height:260px;display:flex;flex-direction:column;justify-content:center;align-items:flex-start;gap:14px}"
"@media(max-width:1100px){.kpis{grid-template-columns:repeat(2,minmax(0,1fr))}}"
"@media(max-width:860px){body{display:block}.rail{position:static;width:100%;min-height:0}.login-slot{display:none}main{margin-left:0;width:100%;padding:16px}.topbar,.grid.two,.chart-grid{display:grid;grid-template-columns:1fr}.topbar-actions{justify-content:space-between}.kpis{grid-template-columns:1fr 1fr}.row,.row.four{grid-template-columns:1fr}.status-line{justify-content:space-between}}";

static const char app_web_js[] =
"const state={registers:[],scanner:null,status:null,editHoldUntil:0};"
"const titles={overview:['Dashboard','Supervision temps reel de la carte industrielle'],registers:['Registres','Lecture et ecriture des holding registers Unit-ID 1'],scanner:['Scanner','Fenetre dynamique Unit-ID 2'],network:['Reseau','Configuration IP future'],security:['Securite','Login et HTTPS prevus phase 8'],firmware:['Firmware','Mise a jour prevue phase 9']};"
"function qs(s){return document.querySelector(s)}"
"function el(t,c,txt){const n=document.createElement(t);if(c)n.className=c;if(txt!==undefined)n.textContent=txt;return n}"
"async function api(path,opts){const r=await fetch(path,opts);if(!r.ok)throw new Error(path);return r.json()}"
"function holdEdit(ms){state.editHoldUntil=Date.now()+ms}"
"function releaseEdit(){state.editHoldUntil=0}"
"function editLocked(){const a=document.activeElement;return Date.now()<state.editHoldUntil||!!(a&&(a.tagName==='INPUT'||a.tagName==='SELECT'))}"
"function setView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===id));qs('#view-title').textContent=titles[id][0];qs('#view-subtitle').textContent=titles[id][1]}"
"function modeName(v){return Number(v)===1?'Static':'DHCP'}"
"function ipFrom(msw,lsw){const a=(msw>>8)&255,b=msw&255,c=(lsw>>8)&255,d=lsw&255;return `${a}.${b}.${c}.${d}`}"
"function regVal(regs,addr,def){return regs[addr]!==undefined?Number(regs[addr]):def}"
"function cfgFromRegs(regs,status){const mode=regVal(regs,1,status.mode||0);return{mode:mode,ip:ipFrom(regVal(regs,2,0),regVal(regs,3,0)),mask:ipFrom(regVal(regs,4,0),regVal(regs,5,0)),gw:ipFrom(regVal(regs,6,0),regVal(regs,7,0))}}"
"function statusCfg(status){return{mode:Number(status.mode||0),ip:status.ip||'0.0.0.0',mask:status.mask||'0.0.0.0',gw:status.gw||'0.0.0.0'}}"
"function sameCfg(a,b){return Number(a.mode)===Number(b.mode)&&a.ip===b.ip&&a.mask===b.mask&&a.gw===b.gw}"
"function regName(addr){const n={0:'Signature device',1:'Mode IP',2:'Adresse IP MSW',3:'Adresse IP LSW',4:'Masque MSW',5:'Masque LSW',6:'Gateway MSW',7:'Gateway LSW',8:'Commande',9:'Statut commande'};if(n[addr])return n[addr];if(addr>=40&&addr<50)return `Scanner map ${addr-40}`;return `Registre libre`}"
"function namedLabel(name,addr){const l=el('label','reg-name');l.append(el('span',null,name));l.append(el('small',null,addr));return l}"
"function mapName(map){if(map===undefined)return '-';return map===65535?'Free':`${regName(map)} (REG${map})`}"
"function putValue(path,value){return api(path,{method:'PUT',headers:{'Content-Type':'application/json'},body:`{\"value\":${Number(value)}}`})}"
"function writeReg(addr,value){return putValue(`/api/registers/${addr}`,value)}"
"function saveConfig(){return api('/api/commands/save-config',{method:'POST'})}"
"async function reboot(){if(!window.confirm('Redemarrer la carte ? La connexion web sera interrompue.'))return;const button=qs('#reboot-button');button.disabled=true;try{await api('/api/commands/reboot',{method:'POST'})}catch(e){button.disabled=false;console.log(e)}}"
"function ipWords(ip){const p=String(ip).split('.').map(Number);if(p.length!==4||p.some(v=>!Number.isInteger(v)||v<0||v>255))throw new Error('ip');return[(p[0]<<8)|p[1],(p[2]<<8)|p[3]]}"
"function sectionTitle(text){return el('div','reg-section',text)}"
"function regRow(addr,value){const row=el('div','row');row.append(namedLabel(regName(addr),`REG${addr}`));const input=el('input');input.type='number';input.min='0';input.max='65535';input.value=value;const btn=el('button',null,'Save');btn.onclick=async()=>{releaseEdit();await writeReg(addr,input.value);await refresh()};row.append(input,btn);return row}"
"function readonlyRow(name,addr,value){const row=el('div','row readonly');row.append(namedLabel(name,addr));row.append(el('code',null,value));return row}"
"function modeRow(value){const row=el('div','row');row.append(namedLabel('Mode IP','REG1'));const sel=el('select');sel.append(new Option('DHCP','0'),new Option('Static','1'));sel.value=String(Number(value)||0);const btn=el('button',null,'Save');btn.onclick=async()=>{releaseEdit();await writeReg(1,sel.value);await refresh()};row.append(sel,btn);return row}"
"function ipRow(name,mswAddr,lswAddr,regs){const row=el('div','row');row.append(namedLabel(name,`REG${mswAddr}+REG${lswAddr}`));const input=el('input');input.inputMode='numeric';input.value=ipFrom(regVal(regs,mswAddr,0),regVal(regs,lswAddr,0));const btn=el('button',null,'Save');btn.onclick=async()=>{try{const w=ipWords(input.value);releaseEdit();await writeReg(mswAddr,w[0]);await writeReg(lswAddr,w[1]);await refresh()}catch(e){holdEdit(30000);input.focus()}};row.append(input,btn);return row}"
"function commandRow(value){const row=el('div','row');row.append(namedLabel('Commande','REST'));const sel=el('select');sel.append(new Option('Aucune','0'),new Option('Save config','1'));sel.value='0';const btn=el('button',null,'Run');btn.onclick=async()=>{releaseEdit();if(sel.value==='1')await saveConfig();await refresh()};row.append(sel,btn);return row}"
"function statusText(value){const v=Number(value);if(v===0)return 'OK';if(v===32767)return 'Pending';return String(v)}"
"function renderRegisterTable(regs){const rt=qs('#register-table');rt.innerHTML='';rt.append(sectionTitle('Configuration decodee'),readonlyRow('Signature device','REG0',`0x${regVal(regs,0,0).toString(16).padStart(4,'0')}`),modeRow(regVal(regs,1,0)),ipRow('Adresse IP',2,3,regs),ipRow('Masque',4,5,regs),ipRow('Gateway',6,7,regs),commandRow(regVal(regs,8,0)),readonlyRow('Statut commande','REG9',statusText(regVal(regs,9,0))),sectionTitle('Mapping scanner'));for(let i=40;i<50;i++)rt.append(regRow(i,regVal(regs,i,0)));rt.append(sectionTitle('Registres libres'));for(let i=10;i<40;i++)rt.append(regRow(i,regVal(regs,i,0)))}"
"function scannerRow(i,map,value){const row=el('div','row four');row.append(namedLabel(`Scanner ${i}`,mapName(map)));const input=el('input');input.type='number';input.min='0';input.max='65535';input.value=value;const btn=el('button',null,'Save');btn.onclick=async()=>{releaseEdit();await putValue(`/api/scanner/${i}`,input.value);await refresh()};row.append(input,btn);return row}"
"function renderDashboardChartA(){const svg=qs('#dashboard-chart-a'),data=[18,24,22,31,36,34,42,47,44,52,58,55,63,68,65,72];if(!svg)return;const pts=data.map((v,i)=>`${20+i*25},${160-v*1.8}`).join(' ');svg.innerHTML=`<defs><linearGradient id=\"trendA\" x1=\"0\" x2=\"0\" y1=\"0\" y2=\"1\"><stop offset=\"0\" stop-color=\"#2f6fed\" stop-opacity=\".22\"/><stop offset=\"1\" stop-color=\"#2f6fed\" stop-opacity=\"0\"/></linearGradient></defs><path d=\"M20 160 L${pts.split(' ').join(' L')} L395 160 Z\" fill=\"url(#trendA)\"/><polyline points=\"${pts}\" fill=\"none\" stroke=\"#2f6fed\" stroke-width=\"4\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/><line x1=\"20\" y1=\"160\" x2=\"400\" y2=\"160\" stroke=\"#d7dde5\"/>`}"
"function renderDashboardChartB(){const svg=qs('#dashboard-chart-b'),data=[38,62,48,76,54,68];if(!svg)return;const bars=data.map((v,i)=>`<g><rect x=\"${42+i*58}\" y=\"${160-v*1.5}\" width=\"30\" height=\"${v*1.5}\" rx=\"4\" fill=\"#2f6fed\"/><text x=\"${57+i*58}\" y=\"174\" text-anchor=\"middle\" fill=\"#667085\" font-size=\"12\">${i+1}</text></g>`).join('');svg.innerHTML=`<line x1=\"24\" y1=\"160\" x2=\"396\" y2=\"160\" stroke=\"#d7dde5\"/>${bars}`}"
"function render(){const s=state.status||{},r=state.registers||[],sc=state.scanner||{},active=statusCfg(s),pending=cfgFromRegs(r,s),isApplied=sameCfg(active,pending);qs('#config-dot').classList.toggle('ok',isApplied);qs('#config-state').textContent=isApplied?'Configuration a jour':'Reboot requis';qs('#kpi-mode').textContent=modeName(active.mode);qs('#kpi-ip').textContent=active.ip||'-';qs('#kpi-connections').textContent=s.modbus_connections!==undefined?s.modbus_connections:'-';qs('#kpi-heartbeat').textContent=s.heartbeat!==undefined?s.heartbeat:'-';renderDashboardChartA();renderDashboardChartB();if(!editLocked()){renderRegisterTable(r);const st=qs('#scanner-table');st.innerHTML='';(sc.values||[]).forEach((v,i)=>st.append(scannerRow(i,(sc.mapping||[])[i],v)))}}"
"let refreshInFlight=false;async function refresh(){if(refreshInFlight)return;refreshInFlight=true;try{const [status,regs,scanner]=await Promise.all([api('/api/status'),api('/api/registers'),api('/api/scanner')]);state.status=status;state.registers=regs.holding||[];state.scanner=scanner;render()}catch(e){console.log(e)}finally{refreshInFlight=false}}"
"document.addEventListener('focusin',e=>{if(e.target.matches('input,select'))holdEdit(30000)});document.addEventListener('input',e=>{if(e.target.matches('input,select'))holdEdit(30000)});document.addEventListener('change',e=>{if(e.target.matches('input,select'))holdEdit(30000)});document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>setView(b.dataset.view));qs('#reboot-button').onclick=reboot;refresh();setInterval(refresh,2000);";

#endif /* APP_WEB_ASSETS_H_ */
