#ifndef APP_WEB_ASSETS_H_
#define APP_WEB_ASSETS_H_

static const char app_web_index_html[] =
"<!doctype html>"
"<html lang=\"fr\">"
"<head>"
"<meta charset=\"utf-8\">"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
"<title>Industrial Ethernet</title>"
"<link rel=\"stylesheet\" href=\"/app.css\">"
"</head>"
"<body>"
"<aside class=\"rail\">"
"<div class=\"brand\"><span class=\"mark\"></span><div><strong>Industrial Ethernet</strong><small>STM32H747 / Zephyr</small></div></div>"
"<nav>"
"<button class=\"nav active\" data-view=\"overview\">Dashboard</button>"
"<button class=\"nav\" data-view=\"registers\">Registres</button>"
"<button class=\"nav\" data-view=\"scanner\">Scanner</button>"
"<button class=\"nav\" data-view=\"network\">Reseau</button>"
"<button class=\"nav\" data-view=\"security\">Securite</button>"
"<button class=\"nav\" data-view=\"firmware\">Firmware</button>"
"</nav>"
"<div class=\"login-slot\"><span></span><div><b>Session locale</b><small>Login prevu phase 8</small></div></div>"
"</aside>"
"<main>"
"<header class=\"topbar\">"
"<div><h1 id=\"view-title\">Dashboard</h1><p id=\"view-subtitle\">Supervision temps reel de la carte industrielle</p></div>"
"<div class=\"status-line\"><span id=\"link-dot\" class=\"dot\"></span><span id=\"active-ip\">0.0.0.0</span><button id=\"refresh\">Rafraichir</button></div>"
"</header>"
"<section id=\"overview\" class=\"view active\">"
"<div class=\"kpis\">"
"<article><span>Mode IP</span><strong id=\"kpi-mode\">-</strong></article>"
"<article><span>Adresse IP</span><strong id=\"kpi-ip\">-</strong></article>"
"<article><span>Lien Ethernet</span><strong id=\"kpi-link\">-</strong></article>"
"<article><span>Connexions Modbus</span><strong id=\"kpi-connections\">-</strong></article>"
"</div>"
"<div class=\"grid two\">"
"<section class=\"panel\"><div class=\"panel-head\"><h2>Registres cle</h2><small>Unit-ID 1</small></div><div id=\"quick-registers\" class=\"compact-table\"></div></section>"
"<section class=\"panel\"><div class=\"panel-head\"><h2>Scanner</h2><small>Unit-ID 2</small></div><div id=\"scanner-summary\" class=\"compact-table\"></div></section>"
"</div>"
"</section>"
"<section id=\"registers\" class=\"view\">"
"<section class=\"panel\"><div class=\"panel-head\"><h2>Holding registers</h2><small>Lecture/ecriture directe</small></div><div id=\"register-table\" class=\"reg-table\"></div></section>"
"</section>"
"<section id=\"scanner\" class=\"view\">"
"<section class=\"panel\"><div class=\"panel-head\"><h2>Fenetre scanner</h2><small>Mapping dynamique registers[50..59]</small></div><div id=\"scanner-table\" class=\"reg-table\"></div></section>"
"</section>"
"<section id=\"network\" class=\"view\"><section class=\"panel placeholder\"><h2>Configuration reseau</h2><p>Cette page accueillera le formulaire DHCP/statique, masque, gateway et sauvegarde persistante.</p><button disabled>Appliquer</button></section></section>"
"<section id=\"security\" class=\"view\"><section class=\"panel placeholder\"><h2>Securite et login</h2><p>Emplacement reserve pour la phase 8 : login, token, changement de mot de passe et HTTPS.</p><button disabled>Connexion</button></section></section>"
"<section id=\"firmware\" class=\"view\"><section class=\"panel placeholder\"><h2>Firmware update</h2><p>Emplacement reserve pour la phase 9 : upload binaire signe, progression et reboot controle.</p><button disabled>Selectionner un firmware</button></section></section>"
"</main>"
"<script src=\"/app.js\"></script>"
"</body>"
"</html>";

static const char app_web_css[] =
":root{--bg:#0f1318;--rail:#151b22;--panel:#f7f8fa;--ink:#17202a;--muted:#667085;--line:#d7dde5;--green:#12a66a;--red:#c84343;--amber:#c48628;--blue:#2f6fed;--steel:#263442}"
"*{box-sizing:border-box}body{margin:0;min-height:100vh;font-family:Inter,Segoe UI,Arial,sans-serif;background:#e9edf2;color:var(--ink);display:flex;letter-spacing:0}"
".rail{width:280px;background:var(--rail);color:#e9eef5;padding:22px 18px;display:flex;flex-direction:column;gap:24px;position:fixed;inset:0 auto 0 0}"
".brand{display:flex;gap:12px;align-items:center}.brand strong{display:block;font-size:17px}.brand small,.login-slot small{display:block;color:#9aa8b8;margin-top:3px}.mark{width:34px;height:34px;border-radius:7px;background:linear-gradient(135deg,#12a66a 0 48%,#f3b44e 48% 100%);box-shadow:0 0 0 1px #ffffff20 inset}"
"nav{display:grid;gap:7px}.nav{height:40px;border:0;border-radius:6px;background:transparent;color:#c7d0dc;text-align:left;padding:0 12px;font-weight:650;cursor:pointer}.nav:hover{background:#202a34}.nav.active{background:#e9eef5;color:#17202a}"
".login-slot{margin-top:auto;border-top:1px solid #2d3744;padding-top:16px;display:flex;gap:10px;align-items:center}.login-slot span{width:10px;height:10px;border-radius:50%;background:var(--amber)}"
"main{margin-left:280px;width:calc(100% - 280px);padding:24px;min-height:100vh}.topbar{display:flex;justify-content:space-between;align-items:center;margin-bottom:20px;gap:16px}h1{font-size:30px;margin:0 0 5px}p{margin:0;color:var(--muted);line-height:1.45}.status-line{display:flex;align-items:center;gap:10px;background:white;border:1px solid var(--line);border-radius:7px;padding:9px 10px}.dot{width:10px;height:10px;border-radius:50%;background:var(--red)}.dot.ok{background:var(--green)}button{border:1px solid #b9c2ce;background:#fff;border-radius:6px;height:34px;padding:0 12px;font-weight:700;color:#263442}button:not(:disabled){cursor:pointer}button:not(:disabled):hover{border-color:#6f7f91}button:disabled{opacity:.55}"
".view{display:none}.view.active{display:block}.kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-bottom:16px}.kpis article,.panel{background:var(--panel);border:1px solid var(--line);border-radius:8px}.kpis article{padding:15px}.kpis span{display:block;color:var(--muted);font-size:13px}.kpis strong{display:block;margin-top:6px;font-size:23px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}"
".grid.two{display:grid;grid-template-columns:1fr 1fr;gap:16px}.panel{padding:16px}.panel-head{display:flex;justify-content:space-between;align-items:baseline;border-bottom:1px solid var(--line);padding-bottom:10px;margin-bottom:12px}.panel h2{font-size:18px;margin:0}.panel small{color:var(--muted)}"
".compact-table,.reg-table{display:grid;gap:6px}.row{display:grid;grid-template-columns:90px 1fr 110px;gap:8px;align-items:center;min-height:34px;padding:6px 8px;background:white;border:1px solid #e1e6ed;border-radius:6px}.row label{font-weight:700;color:#334155}.row code{color:#59677a}.row input{width:100%;height:30px;border:1px solid #cbd3df;border-radius:5px;padding:0 8px;background:#fbfcfe}.row button{height:30px}.row.four{grid-template-columns:80px 1fr 1fr 110px}.placeholder{min-height:260px;display:flex;flex-direction:column;justify-content:center;align-items:flex-start;gap:14px}"
"@media(max-width:860px){body{display:block}.rail{position:static;width:100%;min-height:0}.login-slot{display:none}main{margin-left:0;width:100%;padding:16px}.topbar,.grid.two{display:grid;grid-template-columns:1fr}.kpis{grid-template-columns:1fr 1fr}.row,.row.four{grid-template-columns:1fr}.status-line{justify-content:space-between}}";

static const char app_web_js[] =
"const state={registers:[],scanner:null,status:null};"
"const titles={overview:['Dashboard','Supervision temps reel de la carte industrielle'],registers:['Registres','Lecture et ecriture des holding registers Unit-ID 1'],scanner:['Scanner','Fenetre dynamique Unit-ID 2'],network:['Reseau','Configuration IP future'],security:['Securite','Login et HTTPS prevus phase 8'],firmware:['Firmware','Mise a jour prevue phase 9']};"
"function qs(s){return document.querySelector(s)}"
"function el(t,c,txt){const n=document.createElement(t);if(c)n.className=c;if(txt!==undefined)n.textContent=txt;return n}"
"async function api(path,opts){const r=await fetch(path,opts);if(!r.ok)throw new Error(path);return r.json()}"
"function setView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===id));qs('#view-title').textContent=titles[id][0];qs('#view-subtitle').textContent=titles[id][1]}"
"function modeName(v){return Number(v)===1?'Static':'DHCP'}"
"function ipFrom(msw,lsw){const a=(msw>>8)&255,b=msw&255,c=(lsw>>8)&255,d=lsw&255;return `${a}.${b}.${c}.${d}`}"
"function regRow(addr,value){const row=el('div','row');row.append(el('label',null,`R${addr}`));const input=el('input');input.type='number';input.min='0';input.max='65535';input.value=value;const code=el('code',null,`0x${Number(value).toString(16).padStart(4,'0')}`);const btn=el('button',null,'Ecrire');btn.onclick=async()=>{await api(`/api/registers/${addr}`,{method:'POST',body:`value=${input.value}`});await refresh()};row.append(input,btn);return row}"
"function scannerRow(i,map,value){const row=el('div','row four');row.append(el('label',null,`S${i}`));row.append(el('code',null,map===65535?'local RAM':`R${map}`));const input=el('input');input.type='number';input.min='0';input.max='65535';input.value=value;const btn=el('button',null,'Ecrire');btn.onclick=async()=>{await api(`/api/scanner/${i}`,{method:'POST',body:`value=${input.value}`});await refresh()};row.append(input,btn);return row}"
"function render(){const s=state.status||{},r=state.registers||[],sc=state.scanner||{};qs('#active-ip').textContent=s.ip||'0.0.0.0';qs('#link-dot').classList.toggle('ok',!!s.link);qs('#kpi-mode').textContent=modeName(s.mode);qs('#kpi-ip').textContent=s.ip||'-';qs('#kpi-link').textContent=s.link?'UP':'DOWN';qs('#kpi-connections').textContent=s.modbus_connections!==undefined?s.modbus_connections:'-';const quick=qs('#quick-registers');quick.innerHTML='';[0,1,2,3,4,5,6,7,8,9].forEach(i=>quick.append(regRow(i,r[i]!==undefined?r[i]:0)));const rt=qs('#register-table');rt.innerHTML='';r.forEach((v,i)=>rt.append(regRow(i,v)));const ss=qs('#scanner-summary');ss.innerHTML='';(sc.values||[]).slice(0,5).forEach((v,i)=>ss.append(scannerRow(i,(sc.mapping||[])[i],v)));const st=qs('#scanner-table');st.innerHTML='';(sc.values||[]).forEach((v,i)=>st.append(scannerRow(i,(sc.mapping||[])[i],v)))}"
"async function refresh(){try{const [status,regs,scanner]=await Promise.all([api('/api/status'),api('/api/registers'),api('/api/scanner')]);state.status=status;state.registers=regs.holding||[];state.scanner=scanner;render()}catch(e){console.log(e)}}"
"document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>setView(b.dataset.view));qs('#refresh').onclick=refresh;refresh();setInterval(refresh,1500);";

#endif /* APP_WEB_ASSETS_H_ */
