#ifndef APP_MOTOR_CONTRACT_H_
#define APP_MOTOR_CONTRACT_H_

#include <stdint.h>

#include "app_ipc_protocol.h"

#define APP_MOTOR_CONTRACT_VERSION 1U
#define APP_MOTOR_COMMAND_WORD_COUNT 10U
#define APP_MOTOR_STATE_WORD_COUNT 12U

enum app_motor_command_word {
	APP_MOTOR_COMMAND_CONTROL = 0U,
	APP_MOTOR_COMMAND_DUTY_PERMILLE = 1U,
	APP_MOTOR_COMMAND_ACCEL_RAMP = 2U,
	APP_MOTOR_COMMAND_DECEL_RAMP = 3U,
	APP_MOTOR_COMMAND_MODE = 4U,
	APP_MOTOR_COMMAND_TIMEOUT_MS = 5U,
	APP_MOTOR_COMMAND_RESERVED_0 = 6U,
	APP_MOTOR_COMMAND_RESERVED_1 = 7U,
	APP_MOTOR_COMMAND_RESERVED_2 = 8U,
	APP_MOTOR_COMMAND_SEQUENCE = 9U,
};

#define APP_MOTOR_COMMAND_ENABLE (1U << 0)
#define APP_MOTOR_COMMAND_RUN (1U << 1)
#define APP_MOTOR_COMMAND_DIRECTION_REVERSE (1U << 2)
#define APP_MOTOR_COMMAND_RESET_FAULT (1U << 3)
#define APP_MOTOR_COMMAND_QUICK_STOP (1U << 4)
#define APP_MOTOR_COMMAND_MODE_REMOTE (1U << 0)
#define APP_MOTOR_COMMAND_MODE_SOURCE_SHIFT 8U
#define APP_MOTOR_COMMAND_MODE_SOURCE_MASK (0xffU << APP_MOTOR_COMMAND_MODE_SOURCE_SHIFT)
#define APP_MOTOR_COMMAND_SOURCE_NONE 0U
#define APP_MOTOR_COMMAND_SOURCE_SHELL 1U
#define APP_MOTOR_COMMAND_SOURCE_MODBUS 2U
#define APP_MOTOR_COMMAND_MODE_SOURCE(source) \
	((uint16_t)(source) << APP_MOTOR_COMMAND_MODE_SOURCE_SHIFT)

#define APP_MOTOR_COMMAND_ACCEL_MIN_PERMILLE_PER_SECOND 1U
#define APP_MOTOR_COMMAND_ACCEL_MAX_PERMILLE_PER_SECOND 10000U
#define APP_MOTOR_COMMAND_DUTY_MIN_PERMILLE 800U
#define APP_MOTOR_COMMAND_DUTY_MAX_PERMILLE 1000U
#define APP_MOTOR_COMMAND_TIMEOUT_MIN_MS 100U
#define APP_MOTOR_COMMAND_TIMEOUT_MAX_MS 10000U

enum app_motor_state_word {
	APP_MOTOR_STATE_FLAGS = 0U,
	APP_MOTOR_STATE_APPLIED_DUTY_PERMILLE = 1U,
	APP_MOTOR_STATE_TARGET_DUTY_PERMILLE = 2U,
	APP_MOTOR_STATE_DIRECTION = 3U,
	APP_MOTOR_STATE_FAULT_CODE = 4U,
	APP_MOTOR_STATE_BUTTONS = 5U,
	APP_MOTOR_STATE_POTENTIOMETER_RAW = 6U,
	APP_MOTOR_STATE_COMMAND_AGE_MS = 7U,
	APP_MOTOR_STATE_LOOP_TIME_MS = 8U,
	APP_MOTOR_STATE_HEARTBEAT = 9U,
	APP_MOTOR_STATE_LAST_ACCEPTED_SEQUENCE = 10U,
	APP_MOTOR_STATE_RESERVED = 11U,
};

#define APP_MOTOR_STATE_FLAG_DISABLED (1U << 0)
#define APP_MOTOR_STATE_FLAG_READY (1U << 1)
#define APP_MOTOR_STATE_FLAG_RUNNING (1U << 2)
#define APP_MOTOR_STATE_FLAG_STOPPING (1U << 3)
#define APP_MOTOR_STATE_FLAG_FAULT (1U << 4)
#define APP_MOTOR_STATE_FLAG_LOCAL (1U << 5)
#define APP_MOTOR_STATE_FLAG_REMOTE (1U << 6)
#define APP_MOTOR_STATE_FLAG_IPC_VALID (1U << 7)
#define APP_MOTOR_STATE_FLAG_REMOTE_TIMEOUT (1U << 8)
#define APP_MOTOR_STATE_FLAG_REMOTE_STOP_LATCH (1U << 9)

struct app_motor_command_message {
	struct app_ipc_frame header;
	uint16_t words_le[APP_MOTOR_COMMAND_WORD_COUNT];
};

struct app_motor_state_message {
	struct app_ipc_frame header;
	uint16_t words_le[APP_MOTOR_STATE_WORD_COUNT];
};

#endif /* APP_MOTOR_CONTRACT_H_ */
