#ifndef OPENER_USER_CONF_H_
#define OPENER_USER_CONF_H_

#include <assert.h>
#include <zephyr/net/socket.h>

#include "typedefs.h"

#define CIP_FILE_OBJECT 0
#define CIP_SECURITY_OBJECTS 0
#define OPENER_IS_DLR_DEVICE 0

#define OPENER_TCPIP_IFACE_CFG_SETTABLE 0
#define OPENER_ETHLINK_INSTANCE_CNT 1
#define OPENER_ETHLINK_LABEL_ENABLE 0
#define OPENER_ETHLINK_CNTRS_ENABLE 0
#define OPENER_ETHLINK_IFACE_CTRL_ENABLE 0

#define OPENER_CIP_NUM_APPLICATION_SPECIFIC_CONNECTABLE_OBJECTS 0
#define OPENER_CIP_NUM_EXPLICIT_CONNS 6
#define OPENER_CIP_NUM_EXLUSIVE_OWNER_CONNS 1
#define OPENER_CIP_NUM_INPUT_ONLY_CONNS 0
#define OPENER_CIP_NUM_INPUT_ONLY_CONNS_PER_CON_PATH 0
#define OPENER_CIP_NUM_LISTEN_ONLY_CONNS 0
#define OPENER_CIP_NUM_LISTEN_ONLY_CONNS_PER_CON_PATH 0
#define OPENER_NUMBER_OF_SUPPORTED_SESSIONS 6

static const MilliSeconds kOpenerTimerTickInMilliSeconds = 10;

#define OPENER_ASSERT(assertion) assert(assertion)

#endif /* OPENER_USER_CONF_H_ */
