#ifndef MODBUS_MAP_H_
#define MODBUS_MAP_H_

#define APP_MODBUS_MAP_SIGNATURE 0x0747U
#define APP_MODBUS_MAP_VERSION 4U

#define APP_MODBUS_HOLDING_REG_COUNT 60
#define APP_MODBUS_INPUT_REG_COUNT 16

#define APP_MB_HREG_SIGNATURE 0
#define APP_MB_HREG_MODE 1
#define APP_MB_HREG_IP_MSW 2
#define APP_MB_HREG_IP_LSW 3
#define APP_MB_HREG_MASK_MSW 4
#define APP_MB_HREG_MASK_LSW 5
#define APP_MB_HREG_GW_MSW 6
#define APP_MB_HREG_GW_LSW 7
#define APP_MB_HREG_COMMAND 8
#define APP_MB_HREG_STATUS 9
#define APP_MB_HREG_MOTOR_MODE 10
#define APP_MB_HREG_MOTOR_CONTROL 11
#define APP_MB_HREG_MOTOR_APPLY 12
#define APP_MB_HREG_MOTOR_TARGET_DUTY 13
#define APP_MB_HREG_MOTOR_ACCEL_RAMP 14
#define APP_MB_HREG_MOTOR_DECEL_RAMP 15
#define APP_MB_HREG_MOTOR_TIMEOUT 16
#define APP_MB_HREG_MOTOR_COMMAND_STATUS 17
#define APP_MB_HREG_MOTOR_COMMAND_SEQUENCE 18
#define APP_MB_HREG_MOTOR_RESERVED 19

#define APP_MB_HREG_MOTOR_STATE_BASE 20
#define APP_MB_HREG_MOTOR_STATE_COUNT 12

#define APP_MB_HREG_SCANNER_INPUT_MAP_BASE 40
#define APP_MB_HREG_SCANNER_INPUT_MAP_COUNT 5
#define APP_MB_HREG_SCANNER_OUTPUT_MAP_BASE 45
#define APP_MB_HREG_SCANNER_OUTPUT_MAP_COUNT 5

#define APP_MB_HREG_APPLICATION_DATA_BASE 50
#define APP_MB_HREG_APPLICATION_DATA_COUNT 10

/* Compatibility aliases for Web and EtherNet/IP pending their phase-10.4 update. */
#define APP_MB_HREG_SCANNER_MAP_BASE APP_MB_HREG_SCANNER_INPUT_MAP_BASE
#define APP_MB_HREG_SCANNER_MAP_COUNT \
	(APP_MB_HREG_SCANNER_INPUT_MAP_COUNT + APP_MB_HREG_SCANNER_OUTPUT_MAP_COUNT)

#define APP_MB_SCAN_MAP_FREE 0xffffU

#define APP_MB_MOTOR_MODE_LOCAL 0U
#define APP_MB_MOTOR_MODE_REMOTE 1U
#define APP_MB_MOTOR_APPLY_COMMAND 1U
#define APP_MB_MOTOR_STATUS_PENDING 0x7fffU

#define APP_MB_IREG_SIGNATURE 0
#define APP_MB_IREG_MAP_VERSION 1
#define APP_MB_IREG_UPTIME_LSW 2
#define APP_MB_IREG_UPTIME_MSW 3
#define APP_MB_IREG_ACTIVE_MODE 4
#define APP_MB_IREG_LINK_STATUS 5
#define APP_MB_IREG_IP_MSW 6
#define APP_MB_IREG_IP_LSW 7
#define APP_MB_IREG_MASK_MSW 8
#define APP_MB_IREG_MASK_LSW 9
#define APP_MB_IREG_GW_MSW 10
#define APP_MB_IREG_GW_LSW 11
#define APP_MB_IREG_HEARTBEAT_LSW 12
#define APP_MB_IREG_LAST_STATUS 13
#define APP_MB_IREG_CONN_COUNT 14
#define APP_MB_IREG_RESERVED 15

#define APP_MB_CMD_NONE 0
#define APP_MB_CMD_SAVE 1

#endif /* MODBUS_MAP_H_ */
