#ifndef MODBUS_MAP_H_
#define MODBUS_MAP_H_

#define APP_MODBUS_MAP_VERSION 1

#define APP_MODBUS_HOLDING_REG_COUNT 32
#define APP_MODBUS_INPUT_REG_COUNT 16

#define APP_MB_HREG_SIGNATURE 0
#define APP_MB_HREG_MODE 1
#define APP_MB_HREG_IP_MSW 2
#define APP_MB_HREG_IP_LSW 3
#define APP_MB_HREG_MASK_MSW 4
#define APP_MB_HREG_MASK_LSW 5
#define APP_MB_HREG_GW_MSW 6
#define APP_MB_HREG_GW_LSW 7
#define APP_MB_HREG_COMMAND 8
#define APP_MB_HREG_STATUS 9

#define APP_MB_IREG_SIGNATURE 0
#define APP_MB_IREG_MAP_VERSION 1
#define APP_MB_IREG_UPTIME_LSW 2
#define APP_MB_IREG_UPTIME_MSW 3
#define APP_MB_IREG_ACTIVE_MODE 4
#define APP_MB_IREG_LINK_STATUS 5
#define APP_MB_IREG_IP_MSW 6
#define APP_MB_IREG_IP_LSW 7
#define APP_MB_IREG_MASK_MSW 8
#define APP_MB_IREG_MASK_LSW 9
#define APP_MB_IREG_GW_MSW 10
#define APP_MB_IREG_GW_LSW 11
#define APP_MB_IREG_HEARTBEAT_LSW 12
#define APP_MB_IREG_LAST_STATUS 13
#define APP_MB_IREG_CONN_COUNT 14
#define APP_MB_IREG_RESERVED 15

#define APP_MB_CMD_NONE 0
#define APP_MB_CMD_SAVE 1

#endif /* MODBUS_MAP_H_ */
